buildscript {
    repositories {
        mavenCentral()
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'
//Only edit below this line, the above code adds and enables the necessary things for Forge to be setup.


version = "1.12.2-1.0.0"
group = "nlblackeagle.dynamictreespalebloom"
archivesBaseName = "DynamicTreesPaleBloom"

sourceCompatibility = targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.


compileJava {
    options.compilerArgs += ['-AoutRefMapFile=' + file("$buildDir/resources/main/mixins.dynamictreespalebloom.refmap.json")]
}


minecraft {
    version = "1.12.2-14.23.5.2838"
    runDir = "run"
    mappings = "snapshot_20171003"
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    flatDir { dirs 'libs' }
}

dependencies {
    deobfCompile "local:geckolib-forge-1.12.2:3.0.31"
    deobfCompile "local:DynamicTrees-1.12.2:0.9.29"
    deobfCompile "local:palebloom:1.0.0"
    deobfCompile "local:defiledlands-1.12.2:1.4.3"
    deobfCompile "local:Baubles-1.12:1.5.2"

    compileOnly "org.spongepowered:mixin:0.8.5"
    compile "org.spongepowered:mixin:0.8.5:processor"
    compileOnly "io.github.llamalad7:mixinextras-common:0.4.1"
    compile "io.github.llamalad7:mixinextras-common:0.4.1"

    deobfCompile "local:`FermiumBooter:1.4.1"
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    manifest {
        attributes(
                'FMLCorePlugin': 'nlblackeagle.dynamictreespalebloom.DynamicTreesPaleBloomPlugin',
                'FMLCorePluginContainsFMLMod': 'true',
                'TweakClass': 'org.spongepowered.asm.launch.MixinTweaker',
                'ForceLoadAsMod': 'true'
        )
    }
}