package nlblackeagle.dynamictreespalebloom.compat;

import mezz.jei.api.IModPlugin;
import mezz.jei.api.IModRegistry;
import mezz.jei.api.JEIPlugin;
import mezz.jei.api.ingredients.VanillaTypes;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.registry.ForgeRegistries;

/**
 * Optional JEI integration. JEI only ever discovers/loads this class itself via its
 * own {@code @JEIPlugin} annotation scan across the classpath, and nothing in this
 * addon's own always-loaded code references it directly - so this is safe to ship
 * even on installs without JEI present at all; it simply never gets touched.
 * <p>
 * Pale Bloom's own CompatJEI only registers info-board text for 4 items (Incense
 * Thorns, Pale Oak Hollow, Pollenhead, Resin Bulb) - "palebloom:live_root" has no
 * info board at all natively, despite coming from an addon-original mechanic
 * (Sucker Roots, generated by {@link nlblackeagle.dynamictreespalebloom.trees.FeatureGenSuckerRoots}
 * under Blooming Pale Oak trees) that a player would otherwise have no in-game way
 * to learn about. This adds one, always on regardless of any feature toggle, since
 * Sucker Root generation itself isn't behind any of them either.
 */
@JEIPlugin
public class PaleBloomJEIPlugin implements IModPlugin {

    @Override
    public void register(IModRegistry registry) {
        Item liveRoot = ForgeRegistries.ITEMS.getValue(new ResourceLocation("palebloom", "live_root"));
        if (liveRoot == null) {
            return;
        }

        registry.addIngredientInfo(new ItemStack(liveRoot), VanillaTypes.ITEM, "jei.dynamictreespalebloom.live_root.desc");
    }
}
